n = input('Digite alguma coisa:')
print('O digitado é alpha numerico?')
print(n.isalnum())
print('O digitado é alphabetico?')
print(n.isalpha())
print('O digitado está em minusculas?')
print(n.islower())
print('O digitado está em maiusculas?')
print(n.isupper())